### ISSUE TITLE
детектор москалей

### ISSUE THREAD

**Issue by FishyFish3r** [TheBreakery/Bloomware-Lite#8]
пацанчики а вы можете пж сделать проверку на украинственность у юзера просто мне например не приятно что какой то москаль играет с таким же читом как и я ну или хотя6ы в игре их выделать как то я хз

**Comment by eternalfrenzy1337** [comment]
поддерживаю

**Comment by Blackflex228** [comment]
пропоную їм в табі зробити приписку "раб"

**Comment by OffeeX** [comment]
без проблем, скоро реалізуємо

**Comment by DiOnFire** [comment]
я сам москаль :^)
